ACTIVATION_COLOR = "red"

MINIMAL_CONTROL_ANGLE = 275
MAXIMAL_CONTROL_ANGLE = 220

MINIMAL_SPEED_MODULUS = 10
MAXIMAL_SPEED_MODULUS = 100

ROTATE_DIRECTION = -1

CONTROL_COLOR_SENSOR_PORT = "F"
SENSORY_MOTOR_PORT = "D"
DRIVING_MOTOR_PORT = "B"
